---
- hosts: all
  gather_facts: no
#    This Order is Important!
# Installing updated default plugins
- import_playbook: fs-sp-3013.yml # Service Pack version 3.0.1.3013
- import_playbook: fs-0-update-plugins.yml

# Install demo license
- import_playbook: fs-demo-license.yml

# Update to 64 bit & Mitigate Spectre & Meltdown
- import_playbook: fs-osup-1222014.yml # Operating System Update Pack version 1.2.2.2014

- import_playbook: fs-restart-service.yml # Restart the services after installation
