---
- hosts: all
  gather_facts: no
#    This Order is Important!
# Installing updated default plugins
- import_playbook: fs-sp-302.yml # Service Pack version 3.0.2
- import_playbook: fs-0-update-plugins.yml

# Install demo license
- import_playbook: fs-demo-license.yml

# Update to 64 bit & Mitigate Spectre & Meltdown
- import_playbook: fs-osup-123.yml # Operating System Update Pack version 1.2.3

- import_playbook: fs-restart-service.yml # Restart the services after installation
