---
- hosts: all
  gather_facts: no

  vars:
    fpi_title: IOC Scanner (2.0.1)
    fpi_name: ForeScout-atc-2.0.1-20010003.fpi
    fpi_dir: atc
    fpi_url: https://updates.forescout.com/support/files/plugins/atc/2.0.1/2.0.1-20010003/ForeScout-atc-2.0.1-20010003.fpi
  tasks:

  - name: Install {{ fpi_title }} {{ fpi_name }} from {{ fpi_dir }}
    ping:

  - name: create /tmp/update
    file:
      path: /tmp/update
      state: directory

  - name: create /tmp/update/{{ fpi_dir }} for {{ fpi_name }}
    file:
      path: /tmp/update/{{ fpi_dir }}
      state: directory

  - name: Copy {{ fpi_name }} and unzip in /tmp/update/{{ fpi_dir }}
    unarchive:
        src: "/Users/james/OneDrive - BlueFort Security Ltd/ForeScout/Software/{{ fpi_name }}"
        dest: /tmp/update/{{ fpi_dir }}

  - name: Install {{ fpi_name }}
    shell: fstool plugin -i /tmp/update/{{ fpi_dir }}/data.zip
    notify:
      - restart fstool service

  handlers:
    - name: restart fstool service
      command: fstool service restart
      ignore_errors: yes
      failed_when: false
