---
- hosts: all
  gather_facts: no
#    This Order is Important!
# Installing updated default plugins
- import_playbook: fs-sp-301.yml # Service Pack version 3.0.1
- import_playbook: fs-update-plugins.yml

# Install demo license
- import_playbook: fs-demo-license.yml

# Update to 64 bit
- import_playbook: fs-osup-122.yml # Operating System Update Pack version 1.2.2
