---
- hosts: all
  gather_facts: no

  vars:
    fpi_title: Install HPS Applications (2.1.4)
    fpi_name: ForeScout-meta-2.1.4-21040037.fpi
    fpi_dir: meta
    fpi_url: https://updates.forescout.com/support/files/plugins/meta/2.1.4/2.1.4-21040037/ForeScout-meta-2.1.4-21040037.fpi

  tasks:

  - name: Install HPS Applications (2.1.4) {{ fpi_name }}
    ping:

  - name: create /tmp/update
    file:
      path: /tmp/update
      state: directory

  - name: create /tmp/update/{{ fpi_dir }} for {{ fpi_name }}
    file:
      path: /tmp/update/{{ fpi_dir }}
      state: directory

  - name: Copy {{ fpi_name }} and unzip in /tmp/update/{{ fpi_dir }}
    unarchive:
        src: "/Users/james/OneDrive - BlueFort Security Ltd/ForeScout/Software/{{ fpi_name }}"
        dest: /tmp/update/{{ fpi_dir }}

  - name: Install {{ fpi_name }}
    shell: fstool plugin -i /tmp/update/{{ fpi_dir }}/data.zip
    notify:
      - restart fstool service

#  handlers:
#    - name: restart fstool service
#      command: fstool service restart
#      ignore_errors: yes
#      failed_when: false
