---
- hosts: all
  #chmconnection: local
  gather_facts: no

  tasks:
  - name: Copy pocupdates.zip to /tmp and unzip
    unarchive:
      src: "/Users/james/OneDrive - BlueFort Security Ltd/ForeScout/pocupdates.zip"
      dest: /tmp/

  - name: Make install.sh executable
    file:
      dest: /tmp/pocupdates/install.sh
      mode: a+x

#  - name: Execute /tmp/pocupdates/install.sh
#    shell: /tmp/pocupdates/install.sh
#    args:
#        chdir: /tmp/pocupdates/
