---
- hosts: all
  gather_facts: no

  vars:
    fpi_title: VMware vSphere (2.0.0)
    fpi_name: ForeScout-vmware-2.0.0-20000037.fpi
    fpi_dir: vmware
    fpi_url: https://updates.forescout.com/support/files/plugins/vmware/2.0.0/2.0.0-20000037/ForeScout-vmware-2.0.0-20000037.fpi

  tasks:
  - name: Install {{ fpi_title }} {{ fpi_name }}
    ping:

  - name: create /tmp/update
    file:
      path: /tmp/update
      state: directory

  - name: create /tmp/update/{{ fpi_dir }} for {{ fpi_name }}
    file:
      path: /tmp/update/{{ fpi_dir }}
      state: directory

  - name: Copy {{ fpi_name }} and unzip in /tmp/update/{{ fpi_dir }}
    unarchive:
        src: "/Users/james/OneDrive - BlueFort Security Ltd/ForeScout/Software/{{ fpi_name }}"
        dest: /tmp/update/{{ fpi_dir }}
    notify:
      - install plugin

  handlers:
    - name: install plugin
      command: fstool plugin -i /tmp/update/{{ fpi_dir }}/data.zip
