---
- hosts: all
  gather_facts: no

  vars:
    fpi_title: 802.1x (4.2.0)
    fpi_name: ForeScout-dot1x-4.2.0-42000551.fpi
    fpi_dir: dot1x
    fpi_url: https://updates.forescout.com/support/files/plugins/dot1x/4.2.0/4.2.0-42000551/ForeScout-dot1x-4.2.0-42000551.fpi
  tasks:

  - name: Install {{ fpi_title }} {{ fpi_name }} from {{ fpi_dir }}
    ping:

  - name: create /tmp/update
    file:
      path: /tmp/update
      state: directory

  - name: create /tmp/update/{{ fpi_dir }} for {{ fpi_name }}
    file:
      path: /tmp/update/{{ fpi_dir }}
      state: directory

  - name: Copy {{ fpi_name }} and unzip in /tmp/update/{{ fpi_dir }}
    unarchive:
        src: "/Users/james/OneDrive - BlueFort Security Ltd/ForeScout/Software/{{ fpi_name }}"
        dest: /tmp/update/{{ fpi_dir }}
    notify:
      - install plugin

  handlers:
    - name: install plugin
      command: fstool plugin -i /tmp/update/{{ fpi_dir }}/data.zip
