---
- hosts: all
  gather_facts: no

  vars:
    fpi_title: DNS Enforce (1.1.5)
    fpi_name: ForeScout-hijack_assist-1.1.5-11050005.fpi
    fpi_dir: hijack_assist
    fpi_url: https://updates.forescout.com/support/files/plugins/dns_enforce/1.1.5/1.1.5-11050005/ForeScout-hijack_assist-1.1.5-11050005.fpi

  tasks:
  - name: Install {{ fpi_title }} {{ fpi_name }}
    ping:

  - name: create /tmp/update
    file:
      path: /tmp/update
      state: directory

  - name: create /tmp/update/{{ fpi_dir }} for {{ fpi_name }}
    file:
      path: /tmp/update/{{ fpi_dir }}
      state: directory

  - name: Copy {{ fpi_name }} and unzip in /tmp/update/{{ fpi_dir }}
    unarchive:
        src: "/Users/james/OneDrive - BlueFort Security Ltd/ForeScout/Software/{{ fpi_name }}"
        dest: /tmp/update/{{ fpi_dir }}
    notify:
      - install plugin

  handlers:
    - name: install plugin
      command: fstool plugin -i /tmp/update/{{ fpi_dir }}/data.zip
