---
- hosts: all
  gather_facts: no

  vars:
    fpi_title: Operating System Update Pack version 1.2.2.2014
    fpi_name: ForeScout-osup-1.2.2.2014-12022014.fpi
    fpi_dir: osup
    fpi_url: https://updates.forescout.com/support/files/plugins/osup/1.2.2.2014/1.2.2.2014-12022014/ForeScout-osup-1.2.2.2014-12022014.fpi
  tasks:

  - name: Install {{ fpi_title }} {{ fpi_name }} from {{ fpi_dir }}
    ping:

  - name: create /tmp/update
    file:
      path: /tmp/update
      state: directory

  - name: create /tmp/update/{{ fpi_dir }} for {{ fpi_name }}
    file:
      path: /tmp/update/{{ fpi_dir }}
      state: directory

  - name: Copy {{ fpi_name }} and unzip in /tmp/update/{{ fpi_dir }}
    unarchive:
        src: "/Users/james/OneDrive - BlueFort Security Ltd/ForeScout/Software/{{ fpi_name }}"
        dest: /tmp/update/{{ fpi_dir }}
    notify:
      - install plugin

  handlers:
    - name: install plugin
      command: fstool plugin -i /tmp/update/{{ fpi_dir }}/data.zip
